### ISSUE TITLE
Unsupported operation: Cannot remove from a fixed-length list on --no-fast-mode

### ISSUE THREAD

**Issue by lvyandev** [fluttercandies/ff_annotation_route#40]
### Platforms

dart

### Description

After upgrading `flutter_lints` to version 3.0.0, the `use_super_parameters` rule has become enabled by default. If it's annotated on a class where `super.params` is used, this may lead to generic errors like following.

```dart
const EditPage({
    super.key,
    super.pageType,
    super.infoId,
  });

pageType:asT<super.pageType>(safeArguments['pageType'],)!,
infoId:asT<super.infoId>(safeArguments['infoId'],)!,
```

### Why

To respect lint rules and also to make the code more concise.

**Comment by zmtzawqlp** [comment]
use `--no-fast-mode`

```
    --[no-]fast-mode                   fast-mode: only analyze base on single dart file, it's fast.
                                       no-fast mode: analyze base on whole packages and sdk, support super parameters and add parameters refer import automatically.
                                       (defaults to on)
```

**Comment by lvyandev** [comment]
Yet another issue happens even without super.
```dart
Unhandled exception:
Unsupported operation: Cannot remove from a fixed-length list
#0      FixedLengthListMixin.removeWhere (dart:_internal/list.dart:46:5)
#1      RouteInfo.constructor (package:ff_annotation_route/src/route_info/route_info.dart:55:18)
#2      RouteInfoBase.caseString (package:ff_annotation_route/src/route_info/route_info_base.dart:56:17)
#3      RouteGeneratorBase.generateFile (package:ff_annotation_route/src/route_generator/route_generator_base.dart:193:25)
#4      generate (package:ff_annotation_route/ff_annotation_route.dart:83:10)
<asynchronous suspension>
#5      main (file:///Users/lvyan/.pub-cache/hosted/pub.dev/ff_annotation_route-10.0.9/bin/main.dart:89:3)
<asynchronous suspension>
```
